// app/layout.tsx
import "~/styles/globals.css";
import { Space_Grotesk } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import AppNav from "~/components/ui/AppNav";

const spacegrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-default",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={spacegrotesk.className}>
          {children}
          <AppNav />
        </body>
      </html>
    </ClerkProvider>
  );
}
